# Generated by Django 3.0.7 on 2021-08-04 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('pk_list', models.BigAutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=30)),
                ('background_color', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('when_created_timestamp', models.CharField(max_length=50)),
                ('when_deleted', models.DateTimeField(blank=True, null=True)),
                ('when_deleted_timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
