# Generated by Django 3.0.7 on 2021-08-04 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todowebapp', '0003_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todowebapp.Lists'),
        ),
    ]
