# Generated by Django 3.0.7 on 2021-08-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todowebapp', '0004_auto_20210804_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_completed',
            field=models.BooleanField(default=0),
        ),
    ]
